### ISSUE TITLE
Bigger catch range and one button to do everything

### ISSUE THREAD

**Issue by git998a** [phate09/ToDoChores#28]
Look at the picture.

Now:
![a](https://user-images.githubusercontent.com/44486581/47644925-78a80280-dbaa-11e8-9974-6208f0815420.jpg)
![b](https://user-images.githubusercontent.com/44486581/47645028-c58bd900-dbaa-11e8-82fc-f71b40f2d546.JPG)

Wish:
![a2](https://user-images.githubusercontent.com/44486581/47645048-d3d9f500-dbaa-11e8-8b88-1a48d8da531d.jpg)
![b2](https://user-images.githubusercontent.com/44486581/47645071-e3593e00-dbaa-11e8-95bd-27dbc087a5b1.jpg)

**Comment by taichunmin** [comment]
@git998a Currently the `SEE_TARGET_DIST` of this mod is 25. Most of `SEE_TARGET_DIST` In game source code is only 20. I think the range is large enough because this mod is a client only mod.

https://github.com/taichunmin/dont-starve-together-game-scripts/search?q=SEE_TARGET_DIST&unscoped_q=SEE_TARGET_DIST
